version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
build:
  project: .\KanbanFlow.CSharpSDK\KanbanFlow.CSharpSDK
  verbosity: normal
test: off
before_build:
  - nuget restore C:\projects\kanbanflow-csharp-sdk\KanbanFlow.CSharpSDK